name: Bioconda CDN Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  Check-Bioconda-Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          # cache: "pip"
      - run: pip install -r requirements.txt
      - id: script
        run: python main.py
      - name: run if sync success
        if: env.result == "0"
        run: |
          echo "Sync success"
          echo ${{ env.output }}
          echo ${{ env.result }}
      - name: run if sync unsuccessful
        if: env.result == "1"
        run: |
          echo "Sync not success"
          echo ${{ env.output }}
          echo ${{ env.result }}
