name: Bioconda CDN Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  Check-Bioconda-Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          # cache: "pip"
      - run: pip install -r requirements.txt
      - id: script
        run: |
          if echo "::set-output name=log::$(python main.py)"; then
            echo "::set-output name=result::true"
          else
            echo "::set-output name=result::false"
          fi
      - run: |
          echo $LOG
          echo $RESULT
        env:
          LOG: "${{ steps.script.outputs.log }}"
          RESULT: "${{ steps.script.outputs.result }}"
